routes/web.php
<?php

use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
   return view('home');
});

Route::middleware(['auth'])->group(function () {

    Route::resource('products', ProductController::class)
        ->middleware(['role:user|admin']);

    Route::delete('products/{id}/force-delete', [ProductController::class, 'forceDelete'])
        ->middleware(['role:admin'])
        ->name('products.force-delete');

    Route::post('products/{id}/restore', [ProductController::class, 'restore'])
        ->middleware(['role:admin'])
        ->name('products.restore');

    Route::post('products/restore-all', [ProductController::class, 'restoreAll'])
        ->middleware(['role:admin'])
        ->name('products.restore-all');
});

Auth::routes();

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory, SoftDeletes;

    protected $casts = [
        'data' => 'array'
    ];

    protected $dates = ['deleted_at'];

    protected $fillable = ['article', 'name', 'status', 'data'];

    public function scopeStatus($query, $value)
    {
        return $query->where('status', $value);
    }

    public function setDataAttribute($value): void
    {
        $data = [];

        foreach ($value as $array_item){
            if(!is_null($array_item['key'])){
                $data[] = $array_item;
            }
        }

        $this->attributes['data'] = json_encode($data);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Product\StoreRequest;
use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $products = Product::withTrashed()->status("available")->get();

        return view('products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $statuses = collect(["available", "unavailable"]);

        return view('products.create', compact('statuses'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreRequest $request)
    {
        Product::create($request->validated());

        return redirect()->route('products.index')->with('message', "Продукт успешно создан!");
    }

    /**
     * Display the specified resource.
     */
    public function show(Product $product)
    {
        $countData = 0;
        if (!empty($product->data)){
            $countData = count($product->data);
        }
        return view('products.show', compact('product', 'countData'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Product $product)
    {
        $statuses = collect(["available", "unavailable"]);
        $countData = 0;
        if (!empty($product->data)){
            $countData = count($product->data);
        }
        return view('products.edit', compact('product', 'statuses', 'countData'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Product $product)
    {
        $data = $request->validate([
            'article' => ['bail', 'required', 'unique:products,article,' . $product->id],
            'name' => ['bail', 'required', 'min:10', 'max:256', 'regex:/^[a-zA-Z0-9]+$/'],
            'status' => ['bail', 'required'],
            'data' => ['bail']
        ]);

        $product->update($data);

        return redirect()->route('products.index')->with('message', "Продукт успешно изменен!");
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Product $product)
    {
        $product->delete();

        return redirect()->route('products.index')->with('message', "Продукт успешно архивирован!");
    }

    public function forceDelete($id)
    {
        Product::where('id', $id)->withTrashed()->forceDelete();

        return redirect()->route('products.index')->with('message', "Продукт успешно удален!");
    }

    public function restore($id)
    {
        Product::where('id', $id)->withTrashed()->restore();

        return redirect()->route('products.index')->with('message', "Продукт успешно восстановлен!");
    }

    public function restoreAll()
    {
        Product::onlyTrashed()->restore();

        return redirect()->route('products.index')->with('message', "Продукты успешно восстановлены!");
    }
}

resources/views/home.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test App</title>
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body class="body-home">
<div class="container container-home">
    <h1 class="h1-home">Добро пожаловать!</h1>
    <p class="p-home">Пожалуйста, зарегистрируйтесь или войдите в систему.</p>
    <a href="{{route('register')}}" class="btn-home">Зарегистрироваться</a>
    <a href="{{route('login')}}" class="btn-home">Войти</a>
</div>
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
@if (session('message'))
    <div class="alert alert-primary" role="alert">
        {{session('message')}}
    </div>
@endif
<header>
    <h1>Админ Панель</h1>
</header>
<section>
    <aside>
        <a class="products" href="{{route('products.index')}}">Продукты</a>
    </aside>

    <main class="body">
        @yield('content')
    </main>
</section>
</body>
</html>

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <h1>Добавить продукт</h1>
    <form action="{{route('products.store')}}" method="post">
        @csrf
        <div class="form-group">
            <label for="name">Артикул</label>
            <input type="text" class="form-control form-control-sm col-6" name="article" required>
            @error('article')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group mt-3">
            <label for="name">Название</label>
            <input type="text" class="form-control form-control-sm col-6" name="name" required>
            @error('name')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group mt-3">
            <label for="name">Статус</label>
            <select class="form-control form-control-sm col-6" name="status">
                @foreach($statuses as $status)
                    <option value="{{$status}}">{{$status}}</option>
                @endforeach
            </select>
            @error('status')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group mt-3">
            <label for="data">Атрибуты</label>
            <div class="form-group dynamic-data">
            </div>
            <button type="button" class="btn btn-primary mt-2 add-data">Добавить атрибут</button>
        </div>
        <div class="form-group mt-5">
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    </form>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')
@section('content')
    <h1>Изменить продукт</h1>
    <form action="{{route('products.update', ['product' => $product])}}" method="post">
        @csrf
        @method('PUT')
        @can('edit product-article')
            <div class="form-group">
                <label for="name">Артикул</label>
                <input type="text" class="form-control form-control-sm col-6" name="article" required value="{{$product->article}}">
                @error('article')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        @endcan
        <div class="form-group mt-3">
            <label for="name">Название</label>
            <input type="text" class="form-control form-control-sm col-6" name="name" required value="{{$product->name}}">
            @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group mt-3">
            <label for="name">Статус</label>
            <select name="status">
                @foreach($statuses as $status)
                    <option value="{{$status}}">{{$status}}</option>
                @endforeach
            </select>
            @error('status')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group mt-3">
            <label for="data">Атрибуты</label>
            @if($countData > 0)
                @for($i = 0; $i < $countData; $i++)
                    <div class="row">
                        <div class="col-md-4">
                            <label for="name">Название: </label>
                            <input type="text" name="data[{{ $i }}][key]" class="form-control"
                                   value="{{ $product->data[$i]['key'] ?? '' }}">
                        </div>
                        <div class="col-md-4">
                            <label for="name">Значение: </label>
                            <input type="text" name="data[{{ $i }}][value]" class="form-control"
                                   value="{{ $product->data[$i]['value'] ?? '' }}">
                        </div>
                    </div>
                @endfor
            @endif
            <div class="form-group dynamic-data">
            </div>
            <input type="hidden" value="{{$countData}}" id="count-data" >
            <button type="button" class="btn btn-primary mt-3 add-data">Добавить атрибут</button>
        </div>
        <div class="form-group mt-4">
            <button type="submit" class="btn btn-primary">Изменить</button>
        </div>
    </form>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="ml-auto text-end">
            <button class="btn btn-primary"><a href="{{ route('products.create') }}" style="color: #fff;">Добавить</a></button>
        </div>
        <div class="row mt-5 pb-5">
            <form action="{{ route('products.restore-all') }}" method="post">
                @csrf
                @method('POST')
                <button class="btn btn-warning mb-3">Восстановить все архивированные продукты</button>
            </form>
            <div class="col-12">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col" style="width: 5%;">#</th>
                        <th scope="col" style="width: 15%;">Артикул</th>
                        <th scope="col" style="width: 15%;">Название</th>
                        <th scope="col" style="width: 10%;">Статус</th>
                        <th scope="col" style="width: 25%;">Атрибуты</th>
                        <th scope="col" style="width: 35%;">Действия</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($products as $product)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $product->article }}</td>
                            <td>{{ $product->name }}</td>
                            <td>{{ $product->status }}</td>
                            <td>
                                @if($product->data)
                                    @foreach($product->data as $property)
                                        <b>{{ $property['key'] }}</b>: {{ $property['value'] }}&nbsp;&nbsp;
                                    @endforeach
                                @endif
                            </td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Product Actions">
                                    @if(empty($product->deleted_at))
                                        <button class="btn btn-warning" style="margin-right: 5px;">
                                            <a href="{{ route('products.edit', ['product' => $product]) }}" style="color: #fff;">Изменить</a>
                                        </button>
                                    @else
                                        <form action="{{ route('products.restore', ['id' => $product->id]) }}" method="post" style="margin-right: 5px;">
                                            @method('post')
                                            @csrf
                                            <button class="btn btn-success">Восстановить</button>
                                        </form>
                                    @endif

                                    @if(empty($product->deleted_at))
                                        <form action="{{ route('products.destroy', ['product' => $product]) }}" method="post" style="margin-right: 5px;">
                                            @method('delete')
                                            @csrf
                                            <button class="btn btn-danger">Архивировать</button>
                                        </form>
                                    @endif

                                    <form action="{{ route('products.force-delete', ['id' => $product->id]) }}" method="post" style="margin-right: 5px;">
                                        @method('delete')
                                        @csrf
                                        <button class="btn btn-danger">Удалить</button>
                                    </form>

                                    <button class="btn btn-info">
                                        <a href="{{ route('products.show', ['product' => $product]) }}" style="color: #fff;">Просмотреть</a>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')
@section('content')
    <h1>{{$product->name}}</h1>
    <div class="form-group">
        <label for="name">Артикул</label>
        <h3>{{$product->article}}</h3>
    </div>
    <div class="form-group">
        <label for="name">Название</label>
        <h3>{{$product->name}}</h3>
    </div>
    <div class="form-group">
        <label for="name">Статус</label>
        <h3>{{$product->status}}</h3>
    </div>
    <div class="form-group">
        <label for="data">Атрибуты</label>
        @if($countData > 0)
            @foreach($product->data as $attribute)
                <div class="row">
                    <div class="col-md-4">
                        <label for="name">Именование: </label>
                        <h4>{{ $attribute['key'] ?? '' }}</h4>
                    </div>
                    <div class="col-md-4">
                        <label for="name">Значение: </label>
                        <h4>{{ $attribute['value'] ?? '' }}</h4>
                    </div>
                </div>
            @endforeach
        @endif
        <div class="form-group dynamic-data">
        </div>
    </div>
    <button class="btn btn-info"><a href="{{route('products.index')}}">Назад</a></button>
    <button class="btn btn-warning"><a href="{{route('products.edit', ['product' => $product])}}">Изменить</a></button>
@endsection